//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrecheManagement.Domain.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrecheManagement.Domain.Messages.ReturnMessages", typeof(ReturnMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address city is required..
        /// </summary>
        public static string ADDRESS_CITY_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_CITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address country is required.
        /// </summary>
        public static string ADDRESS_COUNTRY_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_COUNTRY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address district is required..
        /// </summary>
        public static string ADDRESS_DISTRICT_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_DISTRICT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address number is required..
        /// </summary>
        public static string ADDRESS_NUMBER_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_NUMBER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address state is required..
        /// </summary>
        public static string ADDRESS_STATE_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_STATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address street is required..
        /// </summary>
        public static string ADDRESS_STREET_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_STREET_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address zip code is invalid..
        /// </summary>
        public static string ADDRESS_ZIP_INVALID {
            get {
                return ResourceManager.GetString("ADDRESS_ZIP_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address zipcode is required..
        /// </summary>
        public static string ADDRESS_ZIP_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_ZIP_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is required..
        /// </summary>
        public static string AGE_REQUIRED {
            get {
                return ResourceManager.GetString("AGE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist a creche with this CNPJ..
        /// </summary>
        public static string ALREADY_EXIST_CRECHE_WITH_CNPJ {
            get {
                return ResourceManager.GetString("ALREADY_EXIST_CRECHE_WITH_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist a creche with this email..
        /// </summary>
        public static string ALREADY_EXIST_CRECHE_WITH_EMAIL {
            get {
                return ResourceManager.GetString("ALREADY_EXIST_CRECHE_WITH_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attendance already was registered today to:.
        /// </summary>
        public static string ATTENDANCE_ALREADY_REGISTERED_TO {
            get {
                return ResourceManager.GetString("ATTENDANCE_ALREADY_REGISTERED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances registered successfully..
        /// </summary>
        public static string ATTENDANCES_REGISTERED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("ATTENDANCES_REGISTERED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances returned successfully..
        /// </summary>
        public static string ATTENDANCES_RETURNED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("ATTENDANCES_RETURNED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization token missing..
        /// </summary>
        public static string AUTHORIZATION_MISSING {
            get {
                return ResourceManager.GetString("AUTHORIZATION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date is required..
        /// </summary>
        public static string BIRTH_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("BIRTH_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom created successfully..
        /// </summary>
        public static string CLASSROOM_CREATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("CLASSROOM_CREATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A classroom with the same name in this year already exists in this creche..
        /// </summary>
        public static string CLASSROOM_EXIST {
            get {
                return ResourceManager.GetString("CLASSROOM_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom not found..
        /// </summary>
        public static string CLASSROOM_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLASSROOM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms returned successfully..
        /// </summary>
        public static string CLASSROOMS_RETURNED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("CLASSROOMS_RETURNED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ is not valid..
        /// </summary>
        public static string CNPJ_INVALID {
            get {
                return ResourceManager.GetString("CNPJ_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CNPJ is required..
        /// </summary>
        public static string CNPJ_REQUIRED {
            get {
                return ResourceManager.GetString("CNPJ_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number invalid. (XX) X XXXX-XXXX.
        /// </summary>
        public static string CONTACT_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("CONTACT_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF is invalid..
        /// </summary>
        public static string CPF_INVALID {
            get {
                return ResourceManager.GetString("CPF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF is required..
        /// </summary>
        public static string CPF_REQUIRED {
            get {
                return ResourceManager.GetString("CPF_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creche identifier is required..
        /// </summary>
        public static string CRECHE_IDENTIFIER_REQUIRED {
            get {
                return ResourceManager.GetString("CRECHE_IDENTIFIER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creche not found..
        /// </summary>
        public static string CRECHE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CRECHE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creche registered successfully..
        /// </summary>
        public static string CRECHE_REGISTERED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("CRECHE_REGISTERED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creche updated successfully..
        /// </summary>
        public static string CRECHE_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("CRECHE_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creches returned successfully..
        /// </summary>
        public static string CRECHES_RETURNED_SUCESSFULLY {
            get {
                return ResourceManager.GetString("CRECHES_RETURNED_SUCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        public static string DEFAULT_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("DEFAULT_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on validation..
        /// </summary>
        public static string DEFAULT_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("DEFAULT_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of these documents are invalid..
        /// </summary>
        public static string DOCUMENTS_INVALID {
            get {
                return ResourceManager.GetString("DOCUMENTS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is required..
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on CNPJ validation..
        /// </summary>
        public static string ERROR_CONSULT_CNPJ {
            get {
                return ResourceManager.GetString("ERROR_CONSULT_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required..
        /// </summary>
        public static string GENDER_REQUIRED {
            get {
                return ResourceManager.GetString("GENDER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is invalid or expired..
        /// </summary>
        public static string INVALID_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep connected required..
        /// </summary>
        public static string KEEPALIVE_REQUIRED {
            get {
                return ResourceManager.GetString("KEEPALIVE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required..
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None student found..
        /// </summary>
        public static string NONE_STUDENT_FOUND {
            get {
                return ResourceManager.GetString("NONE_STUDENT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 8 and 24 characters..
        /// </summary>
        public static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token expired..
        /// </summary>
        public static string REFRESH_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token generated successfully..
        /// </summary>
        public static string REFRESH_TOKEN_GENERATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_GENERATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of this students was not found..
        /// </summary>
        public static string SOME_STUDENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SOME_STUDENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This student already is on this classroom..
        /// </summary>
        public static string STUDENT_ALREADY_ON_THIS_CLASSROOM {
            get {
                return ResourceManager.GetString("STUDENT_ALREADY_ON_THIS_CLASSROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studend already is registered on this classroom:.
        /// </summary>
        public static string STUDENT_EXIST_ON_THIS_CLASSROOM {
            get {
                return ResourceManager.GetString("STUDENT_EXIST_ON_THIS_CLASSROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist a student on this creche with this CPF..
        /// </summary>
        public static string STUDENT_EXIST_WITH_CPF {
            get {
                return ResourceManager.GetString("STUDENT_EXIST_WITH_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student not found..
        /// </summary>
        public static string STUDENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("STUDENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student registered successfully..
        /// </summary>
        public static string STUDENT_REGISTERED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("STUDENT_REGISTERED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following students are already registered in this classroom:.
        /// </summary>
        public static string STUDENTS_EXIST_ON_THIS_CLASSROOM {
            get {
                return ResourceManager.GetString("STUDENTS_EXIST_ON_THIS_CLASSROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students inserteds on classroom..
        /// </summary>
        public static string STUDENTS_INSERTEDS_ON_CLASSROOM {
            get {
                return ResourceManager.GetString("STUDENTS_INSERTEDS_ON_CLASSROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students returned successfully..
        /// </summary>
        public static string STUDENTS_RETURNED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("STUDENTS_RETURNED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist a registered user with this email..
        /// </summary>
        public static string USER_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("USER_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged successfully..
        /// </summary>
        public static string USER_LOGGED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("USER_LOGGED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully..
        /// </summary>
        public static string USER_REGISTERED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("USER_REGISTERED_SUCCESSFULLY", resourceCulture);
            }
        }
    }
}
